### ISSUE TITLE
Readme feedback

### ISSUE THREAD

**Issue by abdulrehmanch** [AsadRasheed-AR/Excel-to-HTML-Python-script#3]
- [x] 1. list down the useable/necessary files in the project with description
- [x] 2. How to install dependences (include proper requirements.txt by using pip freeze command)
- [x] 3. How to run the code. (After updating the code should take input file as path and output file as path

**Comment by AsadRasheed-AR** [comment]
1- Necessary files and their description has been added in the readme.
2- Dependencies can be installed using pip3, and version of dependencies/libraries is mentioned in the readme file.
3- Example to run the code according to the files in the current repository has been added in the readme, however this example can be used to run the code with different excel/csv files in that scenario filename of the Excel/CSV will be changed however filename of html file will remain same.
